shopquik/login/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signin/$', views.signin, name="signin"),
    url(r'^signup/$', views.signup, name="signup"),
    url(r'^signin/profile/$',views.profile,name="profile"),
    url(r'^signin/profile/createlist/$',views.createlist,name="createlist"),
    url(r'^signin/profile/updatestore/$',views.updatestore,name="updatestore"),
    url(r'^signin/profile/list/$',views.addItems,name="addItem"),
    url(r'^signin/profile/list/stores/$',views.stores,name="stores"),
    url(r'^signin/profile/list/stores/map$',views.map,name="map")

]

shopquik/shopquik/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.homepage, name="homepage"),
    url(r'^login/', include('login.urls',namespace="login")),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^admin/', admin.site.urls),
    # url(r'^stores/$', views.stores),
    url(r'^list/', views.list)
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

shopquik/login/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractBaseUser,  UserManager
from django.forms import ModelForm
# Create your models here.


class Item(models.Model):
    item_name = models.CharField(max_length=30)

    def __str__(self):
        return self.item_name

class List(models.Model):
    list_name = models.CharField(max_length=30)
    items = models.ManyToManyField(Item, null=True,blank=True)

    def __str__(self):
        return self.list_name

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    lists = models.ForeignKey(List, on_delete=models.CASCADE,null=True, blank=True )

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name

class Aisle(models.Model):
    number = models.IntegerField()
    items = models.ManyToManyField(Item)

    def __str__(self):
        return str(self.number)

class Store(models.Model):
    store_name = models.CharField(max_length=30)
    address = models.CharField(max_length=100)
    aisles = models.ManyToManyField(Aisle, null=True, blank=True)

    def __str__(self):
        return self.store_name


#create an associated profile everytime a user is created
def create_profile(sender, **kwargs):
    user = kwargs["instance"]
    if kwargs["created"]:
        user_profile = Profile(user=user)
        user_profile.save()

post_save.connect(create_profile, sender=User)

# class UserForm(ModelForm):
#     class Meta:
#         model = User
#         fields = ['first_name', 'last_name', 'email']
#
# class ItemForm(ModelForm):
#     class Meta:
#         model = Item
#         fields = ['item_name']

shopquik/shopquik/models.py
from django.db import models

# Create your models here.

#
# class List(models.Model):
#     list_name = models.CharField(max_length=30)
#     items = models.ManyToManyField(Item)
#
# class Item(models.Model):
#     item_name = models.CharField(max_length=30)
#
# class Stores(models.Model):
#     store_name = models.CharField(max_length=30)
#     aisles = models.ForeignKey(Aisle, on_delete=models.CASCADE)
#
# class Aisle(models.Model):
#     number = models.IntegerField()
#     items = models.ManyToManyField(Item)
#
# class User(models.Model):
#     first_name = models.CharField(max_length=30)
#     last_name = models.CharField(max_length=30)
#     email = models.EmailField(max_length=100)
#     lists = models.ForeignKey(List, on_delete=models.CASCADE, required=False)

shopquik/login/forms.py
from django.forms import ModelForm
from django import forms
from login.models import *


class UserForm(forms.ModelForm):
    """
    Form for registering a new account.
    """
    # username = forms.CharField(max_length=30)
    email = forms.EmailField(widget=forms.EmailInput,label="email")
    password = forms.CharField(widget=forms.PasswordInput,label="password")

    class Meta:
        model = User
        fields = ['first_name','last_name','email', 'password']

class SignInForm(forms.Form):
    """
    Login form
    """
    email = forms.EmailField(widget=forms.widgets.TextInput)
    password = forms.CharField(widget=forms.widgets.PasswordInput)

    class Meta:
        fields = ['email', 'password']

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name']

class ListForm(ModelForm):
    class Meta:
        model = List
        fields = ['list_name']

shopquik/login/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.utils.text import slugify
from .forms import *
from django.contrib.auth.hashers import make_password
from .models import *
import requests
import json

from . import graph
from shutil import copyfile
import os

def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

# def signin(request):
#     return render(request, "shopquik/signin.html/")

def signup(request):
    if request.method == 'POST':
        if 'user_submit' in request.POST:
            user_form = UserForm(request.POST)

            if user_form.is_valid():

                first_name = request.POST.get('first_name')
                last_name = request.POST.get('last_name')
                email = request.POST.get('email')
                password = request.POST.get('password')
                user = User(first_name = first_name, last_name = last_name, email = email, username=email)
                user.set_password(password)
                user.save()
                profile = Profile.objects.get(user=user)
                profile.save()
                # sign_up = user_form.save(commit=False)
                # sign_up.password = make_password(user_form.cleaned_data['password'])
                # sign_up.status = 1
                # sign_up.save()
                return HttpResponse("Submitted!")
        else:
            user_form = UserForm()
            return render(request, 'shopquik/login/signup.html/', {'user_form':user_form})
    else:
        user_form = UserForm()
    return render(request, "shopquik/signup.html/",{'user_form':user_form})

def signin(request):
    if request.method == 'POST':
        if 'signin_submit' in request.POST:
            signin_form = SignInForm(request.POST)
            if signin_form.is_valid():
                data = signin_form.cleaned_data
                email = request.POST.get('email')
                password = request.POST.get('password')
                user = authenticate(username =data['email'] , password = data['password'])
                print("MESSAGE: ", email)
                print("MESSAGE: ", password)
                print("MESSAGE: ", authenticate(username =data['email'] , password = data['password']))
                print("MESSAGE: User is - ", user)
                if user is not None:
                    login(request, user)
                    list_form = ListForm()
                    return render(request,'shopquik/profile.html/', {
                        'user': user,
                        'list_form':list_form
                    })
                else:
                    # Return an 'invalid login' error message.
                    return HttpResponse("Sign in Error!")
        else:
            signin_form = SignInForm()
            return render(request, 'shopquik/login/signin.html/', {'signin_form':signin_form})
    else:
        signin_form = SignInForm()
    return render(request, "shopquik/signin.html/",{'signin_form':signin_form})

def createlist(request):
    if request.method == 'POST':
        if 'list_submit' in request.POST:
            list_form = ListForm(request.POST)
            list_name = request.POST.get('list_name')
            if list_form.is_valid():
                request.session['list_name'] = list_form.data['list_name']
                item_form = ItemForm()
                list_form.save()
                return render(request,'shopquik/list.html',{
                    'list_name': list_name,
                    'item_form': item_form
                })
            else:
                list_form = ListForm()
                return render(request, 'shopquik/createlist.html/', {'list_form':list_form})
        else:
            list_form = ListForm()
            return render(request,'shopquik/createlist.html/', {'list_form':list_form})
    else:
        list_form = ListForm()
    return render(request, "shopquik/createlist.html/",{'list_form':list_form})

def addItems(request):
    # list_name = request.POST.get('list_name')
    list_name = request.session['list_name']
    list = List.objects.filter(list_name=list_name)
    if request.method == 'POST':
        if 'item_submit' in request.POST:
            item_form = ItemForm(request.POST)
            if item_form.is_valid():
                i = item_form.save()
                list[0].items.add(i)
                item_form = ItemForm()

                # return HttpResponse("Items saved!")
                return render(request,'shopquik/list.html/',{'item_form':item_form,'list_name':list_name,'lists':list})
            else:
                item_form = ItemForm()
                return render(request,'shopquik/list.html/',{'item_form':item_form,'list_name':list_name,'lists':list})
        elif 'item_delete' in request.POST:
            items = Item.objects.filter(item_name=request.POST.get('item_delete'))
            for item in items:
                for l in list:
                    l.items.remove(item)

            item_form = ItemForm()
            return render(request, 'shopquik/list.html/',
                          {'item_form': item_form, 'list_name': list_name, 'lists': list})
        else:
            item_form = ItemForm()
            return render(request,'shopquik/list.html/',{'item_form':item_form,'list_name':list_name,'lists':list})
    else:
        item_form = ItemForm()
    return render(request,'shopquik/list.html/',{'item_form':item_form,'list_name':list_name,'lists':list})

def stores(request):
    list_name = request.session['list_name']
    if request.method == 'POST':
        address = request.POST.get("address", "")
        requestString = "https://maps.googleapis.com/maps/api/geocode/json?address="+ str(address) +"&key=AIzaSyAwpVMPCRmLfoa7CxGQr4SrmmkwPm4iiSE"
        locdata = requests.get(requestString, timeout=1)
        loc = json.loads(locdata.text)['results'][0]['geometry']['location']
        location = str(loc['lat']) + ',' + str(loc['lng'])
        data = requests.get("https://maps.googleapis.com/maps/api/place/nearbysearch/json?location="+ str(location) +"&radius=5000&keyword=Stater&key=AIzaSyC5Ygtct3M5odZ_iu45po0Rby9I3VEpLZc")
        stores = json.loads(data.text)['results']
    else:
        stores = ""
    return render(request, 'shopquik/store.html/', {
        "store_list": stores,
        "list": list,
        "list_name":list_name
    })

def map(request):
    list_name = request.session['list_name']
    address = request.POST.get("address", "")
    print("MESSAGE: address ",address)
    list = List.objects.filter(list_name=list_name)
    stores = Store.objects.filter(address=address)
    print("stores: ",stores)
    aisles_used=[]
    store_name = ""
    for store in stores:
        print("MESSAGE: ", store)
        store_name = store.store_name
        aisles = store.aisles.all()
        for aisle in aisles:
            for item in list[0].items.all():
                for i in aisle.items.all():
                    if i.item_name == item.item_name:
                        if aisle not in aisles_used:
                            aisles_used.append(aisle)

    print("aisles: ", aisles_used)
    map_aisles = [aisle.number for aisle in aisles_used]
    map_img_filename = graph.draw_map(slugify(store_name), map_aisles)
    copyfile(map_img_filename, 'login/static/shopquik/images/cur_map.jpeg')

    return render(request, 'shopquik/map.html',{
        'list':list,
        'store_name':store_name,
        # 'aisles':aisles,
        'aisles_used':aisles_used,
        'map_name':'cur_map.jpeg'
    })

def profile(request):
    return render(request,'shopquik/profile.html')


# def createlist(request):
#     return render(request,'shopquik/createlist.html')

def updatestore(request):
    list_name = request.session['list_name']
    if request.method == 'POST':
        address = request.POST.get("address", "")
        requestString = "https://maps.googleapis.com/maps/api/geocode/json?address="+ str(address) +"&key=AIzaSyAwpVMPCRmLfoa7CxGQr4SrmmkwPm4iiSE"
        locdata = requests.get(requestString, timeout=1)
        loc = json.loads(locdata.text)['results'][0]['geometry']['location']
        location = str(loc['lat']) + ',' + str(loc['lng'])
        data = requests.get("https://maps.googleapis.com/maps/api/place/nearbysearch/json?location="+ str(location) +"&radius=5000&keyword=Stater&key=AIzaSyC5Ygtct3M5odZ_iu45po0Rby9I3VEpLZc")
        stores = json.loads(data.text)['results']
    else:
        stores = ""
    return render(request, 'shopquik/store.html/', {
        "store_list": stores,
        "list": list,
        "list_name":list_name
    })

    # return render(request,'shopquik/updatestore.html')

shopquik/shopquik/views.py
from django.shortcuts import render
from django.contrib import auth
import requests
import json

def homepage(request):
    return render(request,'shopquik/homepage.html/')

def logout(request):
    auth.logout(request)
    return render(request, "shopquik/homepage.html")
# def stores(request):
#     list_name = request.session['list_name']
#     if request.POST:
#         if(request.POST.get("address", "")):
#             address = request.POST.get("address", "")
#             locdata = requests.get("https://maps.googleapis.com/maps/api/geocode/json?address="+ str(address) +"&key=AIzaSyAwpVMPCRmLfoa7CxGQr4SrmmkwPm4iiSE")
#             loc = json.loads(locdata.text)['results'][0]['geometry']['location']
#             location = str(loc['lat']) + ',' + str(loc['lng'])
#             data = requests.get("https://maps.googleapis.com/maps/api/place/nearbysearch/json?location="+ str(location) +"&radius=5000&keyword=Stater&key=AIzaSyC5Ygtct3M5odZ_iu45po0Rby9I3VEpLZc")
#             stores = json.loads(data.text)['results']
#     else:
#         stores = ""
#     # list = List.objects.filter(list_name=list_name)
#     return render(request, 'shopquik/store.html/', {
#         "store_list": stores,
#         "list": list
#     })

def list(request):
    list = List.object
    return render(request, 'shopquik/list.html/', {
        "list": list
    })

shopquik/login/templates/shopquik/createlist.html
profile.html{% extends 'shopquik/global.html' %}


{% block main_content %}
<h1>Welcome {{ user.first_name }}</h1>

<h3>Create a new shopping list:</h3>

  <form action="{% url 'login:createlist' %}" method="post">
    {% csrf_token %}
    {{ list_form }}
    <input type="submit" class="btn btn-success" name="list_submit" value="Submit" />
</form>

{% endblock %}

shopquik/login/templates/shopquik/global.html
<!DOCTYPE html>
<html lang="en">
<head>
    <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    {% load staticfiles %}
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">-->
    <link rel="stylesheet" type ="text/css" href="{% static 'shopquik/css/bootstrap.min.css' %}"/>
    <script src="{% static 'shopquik/js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'shopquik/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'shopquik/js/moment-2.17.1.js' %}"></script>
    <script src="{% static 'shopquik/js/bootstrap-datetimepicker.js' %}"></script>
    <script src="{% static 'shopquik/js/bootstrap-datepicker.js' %}"></script>
  </head>
</head>
<body style="min-height:100%">
 <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">ShopQuik</a>
        </div>
       <!--/.navbar-collapse -->

          <div class="navbar-form navbar-right">
              {% if user.is_authenticated %}
              <a class="btn btn-warning" href="/logout">Logout</a>
              {% else %}
              <a class="btn btn-success" href="/login/signin">Sign in</a>
              <a class="btn btn-primary" href="/login/signup">Sign up</a>
              {% endif %}
          </div>
      </div>
    </nav>
<div style="margin-top:50px">
    {% block main_content %}
      {% endblock %}
    </div>
</body>

shopquik/login/templates/shopquik/homepage.html
{% extends 'shopquik/global.html' %}


{% block main_content %}
  <div class="jumbotron">
      <div class="container text-center">
        <h1>Welcome to ShopQuik</h1>
        <p></p>
        {% if user.is_authenticated %}
        <p><a class="btn btn-primary btn-lg" href="/login/signin/profile" role="button">Get Started &raquo;</a></p>
        {% else %}
        <p><a class="btn btn-primary btn-lg" href="/login/signin" role="button">Get Started &raquo;</a></p>
        {% endif %}
      </div>
    </div>
{% endblock %}

shopquik/login/templates/shopquik/homepage_template.html
<!DOCTYPE html>
<html lang="en">
{% extends 'shopquik/global.html' %}
  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">ShopQuik</a>
        </div>
       <!--/.navbar-collapse -->
          <div class="navbar-form navbar-right">
          <button type="submit" class="btn btn-success">Sign in</button>
          <button type="submit" class="btn btn-primary">Sign up</button>
          </div>
      </div>
    </nav>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container text-center">
        <h1>Welcome to ShopQuik</h1>
        <p></p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Get Started &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <hr>
      <div>
      {% block main_content %}
      {% endblock %}
      </div>
      <footer>
        <hr>
        <p>HackPoly 2017</p>
      </footer>
    </div> <!-- /container -->

  </body>
</html>

shopquik/login/templates/shopquik/list.html
<!DOCTYPE html>
<html lang="en">
{% extends 'shopquik/global.html' %}
<body>
{% block main_content %}
<h1>{{ list_name }}</h1>
<div>
    <form action="{% url 'login:addItem' %}" method="post">
    {% csrf_token %}
    {{ item_form }}
        <input type="hidden" name="list_name" value="{{ list_name }}">
        <button type="submit" class="btn btn-success" name="item_submit" value="Submit">Add</button>
    </form>
</div>
<div class="list-container">
    <table class="table table-striped">
        {% for list in lists %}
            {% for item in list.items.all %}
                <form action="{% url 'login:addItem' %}" method="post">
                    {% csrf_token %}
                    <p>{{ item.item_name }} <button type="submit" class="btn btn-danger" name="item_delete" value="{{item.item_name}}">X</button></p>
                </form>
            {% endfor %}
        {% endfor %}
    </table>
        <a href="{% url 'login:stores' %}" class="btn btn-success" >Done</a>
</div>
{% endblock %}
</body>
</html>

shopquik/login/templates/shopquik/map.html
<!DOCTYPE html>
<html lang="en">
{% extends 'shopquik/global.html' %}
<body>
{% block main_content %}
<h1 class="text-center" style="padding-top:20px">{{ store_name }} ShopQuik Guide</h1>
{% load staticfiles %}
<image src="{% static 'shopquik/images/cur_map.jpeg' %}" alt="Missing" height="600" width="80%">
<h2 class="text-center">QuikStops</h2>
<table class="table text-center">
    {% for aisle in aisles_used %}
    <tr>
        <td>Aisle {{ aisle.number }}</td>

        <td>{% for item in list.0.items.all %}
                {% for i in aisle.items.all %}
                    {% if i.item_name == item.item_name %}
                        <p>{{ item }}</p>
                    {% endif %}
                {% endfor %}
            {% endfor %}
        </td>
    </tr>
    {% endfor %}
</table>
</body>
{% endblock %}
</html>

shopquik/login/templates/shopquik/profile.html
{% extends 'shopquik/global.html' %}


{% block main_content %}
<h1>Welcome {{ user.first_name }}</h1>

<h3>Create a new shopping list:</h3>

<a href="{% url 'login:createlist' %}">Create List</a>
<a href="{% url 'login:updatestore' %}">Update Store</a>

{% endblock %}

shopquik/login/templates/shopquik/signin.html
{% extends 'shopquik/global.html' %}


{% block main_content %}
<h1>Login:</h1>
<form action="{% url 'login:signin' %}" method="post">
    {% csrf_token %}
    {{ signin_form }}
    <input type="submit" class="btn btn-default" name="signin_submit" value="Submit" />
</form>

{% endblock %}

shopquik/login/templates/shopquik/signup.html
{% extends 'shopquik/global.html' %}


{% block main_content %}
<form action="{% url 'login:signup' %}" method="post">
    {% csrf_token %}
    {{ user_form }}
    <input type="submit" class="btn btn-default" name="user_submit" value="Submit" />
</form>

{% endblock %}

shopquik/login/templates/shopquik/store.html
<!DOCTYPE html>
<html lang="en">
{% extends 'shopquik/global.html' %}
<body>
{% block main_content %}
<h1>Store Locator</h1>
<form action="{% url 'login:stores' %}" method="POST">
    {% csrf_token %}
    <label>Enter Zip:</label>
    <input type="text" name="address">
    <button class="btn btn-primary" type="submit">Search</button>
</form>
<table>
{% for store in store_list %}
<tr>
    <form action="{% url 'login:map' %}" method="POST">
        {% csrf_token %}
    <td>{{ store.name }}</td>
    <td>{{ store.vicinity }}<input type="hidden" name="address" value="{{ store.vicinity }}"></td>
    <td><button class="btn btn-success" type="submit">Select</button></td>
    </form>
</tr>
{% endfor %}
</table>
{% endblock %}
</body>
</html>

shopquik/login/templates/shopquik/updatestore.html
<!DOCTYPE html>
<html lang="en">
{% extends 'shopquik/global.html' %}
<body>
{% block main_content %}
<h1>Store Locator</h1>
<form action="{% url 'login:stores' %}" method="POST">
    {% csrf_token %}
    <label>Enter Zip:</label>
    <input type="text" name="address">
    <button class="btn btn-primary" type="submit">Search</button>
</form>
<table>
{% for store in store_list %}
<tr>
    <form action="{% url 'login:updatestore' %}" method="POST">
        {% csrf_token %}
    <td>{{ store.name }}</td>
    <td>{{ store.vicinity }}<input type="hidden" name="address" value="{{ store.vicinity }}"></td>
    <td><button class="btn btn-success" type="submit">Select</button></td>
    </form>
</tr>
{% endfor %}
</table>
{% endblock %}
</body>
</html>